// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU0hEDlC7mzsyIyubUAujh3KRNoKyM7lo',
    appId: '1:521222126341:web:2c0ca65351a8c51ab2956c',
    messagingSenderId: '521222126341',
    projectId: 'final-year-project-b467d',
    authDomain: 'final-year-project-b467d.firebaseapp.com',
    storageBucket: 'final-year-project-b467d.firebasestorage.app',
    measurementId: 'G-4NWZXDHRMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2KSIa4cx4MHKWjQ9cc09OM5JMchoceb4',
    appId: '1:521222126341:android:a8bf0c011bffcaafb2956c',
    messagingSenderId: '521222126341',
    projectId: 'final-year-project-b467d',
    storageBucket: 'final-year-project-b467d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBN9BasuA1Y71RO218pegwAl0DpTZIRpU',
    appId: '1:521222126341:ios:52248366aea20a32b2956c',
    messagingSenderId: '521222126341',
    projectId: 'final-year-project-b467d',
    storageBucket: 'final-year-project-b467d.firebasestorage.app',
    iosClientId: '521222126341-9in2pvlorcl5217284g283p9h1spg14d.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBN9BasuA1Y71RO218pegwAl0DpTZIRpU',
    appId: '1:521222126341:ios:52248366aea20a32b2956c',
    messagingSenderId: '521222126341',
    projectId: 'final-year-project-b467d',
    storageBucket: 'final-year-project-b467d.firebasestorage.app',
    iosClientId: '521222126341-9in2pvlorcl5217284g283p9h1spg14d.apps.googleusercontent.com',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU0hEDlC7mzsyIyubUAujh3KRNoKyM7lo',
    appId: '1:521222126341:web:0e0284741915ea64b2956c',
    messagingSenderId: '521222126341',
    projectId: 'final-year-project-b467d',
    authDomain: 'final-year-project-b467d.firebaseapp.com',
    storageBucket: 'final-year-project-b467d.firebasestorage.app',
    measurementId: 'G-RS6N5GTMJE',
  );
}
